### ISSUE TITLE
It seems do not work with https protocol

### ISSUE THREAD

**Issue by liyun935cn** [K-GmbH/licodeAndroidClient#6]
My licode is working under https protocol, when I click "Videochat OFF" menu, there is error below:

`06-13 18:01:55.318 4708-7552/com.example.licodeclient W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
06-13 18:01:55.332 4708-7552/com.example.licodeclient W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:322)
06-13 18:01:55.332 4708-7552/com.example.licodeclient W/System.err:     at com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
06-13 18:01:55.332 4708-7552/com.example.licodeclient W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:155)
06-13 18:01:55.332 4708-7552/com.example.licodeclient W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
06-13 18:01:55.332 4708-7552/com.example.licodeclient W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
06-13 18:01:55.332 4708-7552/com.example.licodeclient W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
06-13 18:01:55.332 4708-7552/com.example.licodeclient W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
06-13 18:01:55.332 4708-7552/com.example.licodeclient W/System.err:     at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
06-13 18:01:55.332 4708-7552/com.example.licodeclient W/System.err:     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
06-13 18:01:55.332 4708-7552/com.example.licodeclient W/System.err:     at com.example.licodeclient.FragmentVideoChat$XmlHttpRequest.doInBackground(FragmentVideoChat.java:492)
06-13 18:01:55.332 4708-7552/com.example.licodeclient W/System.err:     at com.example.licodeclient.FragmentVideoChat$XmlHttpRequest.doInBackground(FragmentVideoChat.java:456)
06-13 18:01:55.333 4708-7552/com.example.licodeclient W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
06-13 18:01:55.333 4708-7552/com.example.licodeclient W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-13 18:01:55.333 4708-7552/com.example.licodeclient W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
06-13 18:01:55.333 4708-7552/com.example.licodeclient W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-13 18:01:55.333 4708-7552/com.example.licodeclient W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-13 18:01:55.333 4708-7552/com.example.licodeclient W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-13 18:01:55.333 4708-7552/com.example.licodeclient W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
06-13 18:01:55.333 4708-7552/com.example.licodeclient W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:324)
06-13 18:01:55.333 4708-7552/com.example.licodeclient W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225)
06-13 18:01:55.333 4708-7552/com.example.licodeclient W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:114)
06-13 18:01:55.334 4708-7552/com.example.licodeclient W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:550)
06-13 18:01:55.334 4708-7552/com.example.licodeclient W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
06-13 18:01:55.334 4708-7552/com.example.licodeclient W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
06-13 18:01:55.334 4708-7552/com.example.licodeclient W/System.err:     ... 16 more
06-13 18:01:55.334 4708-7552/com.example.licodeclient W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
06-13 18:01:55.334 4708-7552/com.example.licodeclient W/System.err:     ... 22 more`

**Comment by evilword666** [comment]
Hi @liyun935cn , are you using port 3004 for the connection to https?
Could you run the app?
